---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-password-secret
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore

  target:
    name: grafana-admin-password-secret
    creationPolicy: Owner

  data:
    - secretKey: GF_SECURITY_ADMIN_PASSWORD
      remoteRef:
        key: Grafana Admin
        property: password
