apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-password-secret
stringData:
    GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:JTuSGnep0WCi,iv:g/ZHSoH1iHVUtrPBha8GnbgwQoTmMod6pzXh6HE27Go=,tag:FxI/atCvhfAInfovdukC9A==,type:str]
sops:
    age:
        - recipient: age1d7fjm42t7d8r9g4glua85tkrf4txswk2hnc8s4pgr8nyupnenfhqmegklw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4MGpGVFBVRHBTWXZUVDlu
            NzN5VVgvZ1A1OGV0d3dHZWwwZzNxUG5Dam1jCkZwWVJCSW5mSm5tVjd2WnVOOVNU
            bnd4d1FBWmhVVHFTVHlvRlJMS0MwNUEKLS0tIGNRYThWbW83REwrSWdXU2lWN0Rj
            SGlSdTEyOGlBaWMxcGNrNU4yRDM5cm8KiLSwErKEXXnZzji9Qv7s/0dz+qjhMWO7
            J1YpTrqpoZGM7YPyS3nA65tX/DNilHuOMKSqSGGPZINAlP+NO9Z1Rg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T15:32:00Z"
    mac: ENC[AES256_GCM,data:VWzE/Us6QcEcccsENPEl0PySBN54yYc7f7tNGTmjs4tl4SzTV6da5PM8RUCp7fa4AaRE+wobgjo5qUTWfdwYofHeaWirnjict23p8eQxaH9CdWoXNaWKY1/J4IBhXkfftE3kZ0l6Sw/sHwGp9MCCf/vhRXZLdGH2jNnFJTLMfS8=,iv:mbUDVRHXKgRwRGC3f46iAB8nkZox9XbBH8C7cp3ELXM=,tag:0T44kzvIEUcKglkSN891Lg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
