[env]
SOPS_AGE_KEY_FILE = '{{config_root}}/age.key'

[tools]
# Kubectl + Plugins
"aqua:kubectl" = "1.35.0"
"aqua:fluxcd/flux2" = "2.8.1"
"aqua:kustomize" = "latest"
"aqua:helm" = "latest"
"aqua:derailed/k9s" = "latest"
clusterctl = "latest"

# Talos Stuff
"aqua:talosctl" = "1.12.0"
"aqua:talhelper" = "3.0.43"

# Terraform Stuff
terragrunt = "latest"
opentofu = "latest"
op = "latest"

# Misc Tools
task = "latest"
sops = "latest"
age = "latest"
direnv = "latest"

# Linters
yamlfmt = "latest"
actionlint = "latest"
shellcheck = "latest"
