[env]
SOPS_AGE_KEY_FILE = '{{config_root}}/age.key'

[tools]
# Kubectl + Plugins
"aqua:kubectl" = "1.35.0"
"aqua:fluxcd/flux2" = "2.7.5"
"aqua:kustomize" = "5.8.0"
"aqua:helm" = "4.0.4"
"aqua:derailed/k9s" = "0.50.16"

# Talos Stuff
"aqua:talosctl" = "1.12.0"
"aqua:talhelper" = "3.0.44"

# Terraform Stuff
"aqua:terraform" = "1.14.3"

# Misc Tools
"aqua:go-task/task" = "3.46.4"
"aqua:getsops/sops" = "3.11.0"
"aqua:FiloSottile/age" = "1.3.1"
