[env]
SOPS_AGE_KEY_FILE = '{{config_root}}/age.key'

[tools]
# Kubectl + Plugins
"aqua:kubectl" = "1.34.1"
"aqua:fluxcd/flux2" = "2.7.3"
"aqua:kustomize" = "5.6.0"
"aqua:helm" = "3.19.0"
"aqua:derailed/k9s" = "0.50.16"

# Talos Stuff
"aqua:talosctl" = "1.11.3"
"aqua:talhelper" = "3.0.38"

# Terraform Stuff
"aqua:terraform" = "1.13"

# Misc Tools
"aqua:go-task/task" = "3.45.4"
"aqua:getsops/sops" = "3.11.0"
"aqua:FiloSottile/age" = "1.2.1"
