[env]
SOPS_AGE_KEY_FILE = '{{config_root}}/age.key'

[tools]
# Kubectl + Tools + Plugins
"aqua:kubectl" = "1.35.1"
"github:mirceanton/kubectl-switch" = "v2.4.3"
"aqua:kustomize" = "latest"
"aqua:derailed/k9s" = "latest"
"aqua:fluxcd/flux2" = "2.7.5"

# Helm + Plugins
"aqua:helm" = "latest"
helmfile = "latest"

# CAPI Tools
clusterctl = "latest"

# Talos Stuff
"aqua:talosctl" = "1.12.4"
"aqua:talhelper" = "3.1.4"
"github:mirceanton/talswitcher" = "latest"

# Misc Tools
task = "latest"
sops = "latest"
age = "latest"
direnv = "latest"
op = "latest"
yq = "latest"

# Linters
yamlfmt = "latest"
actionlint = "latest"
shellcheck = "latest"
