---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage-system

resources:
  - ./helm-release.yaml
  - ./oci-repository.yaml
  - ./snapshot-class.yaml
  - ./storage-class.yaml
