---
# ===============================================
# ANSIBLE CONFIGURATION
# ===============================================
ansible_host: 192.168.10.69
ansible_user: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          30306636303732306466346135376565363135626230623434623030323330656362303536663838
          3436386336386464323666323831313665373032396665640a386363333536626363303530303461
          35646266383666313264626463303862373736353433316431383735623332333333383232353765
          6261353436303239380a366466323734626363393337616332373034326434353531623731663062
          6533
ansible_ssh_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          36303437343437623137653631656539363030623164643066633062376632613631653739383061
          6534396337383066343863373433623432333562383835640a343233336135393932653231396537
          31643563323438656533356334323764636330326634373836613833356438636130623764623763
          6233393034396339630a353632643438306639613266313436643561333237663838343065393330
          33313962333963636638336365643333333163383064333830653962303165666662323930636636
          34343765663630396538343766393465633034303039313264383533356439373236353432343235
          63346334366634663631653537613631326366343230643635313732383034383839333364356439
          37396338633331396562

# ===============================================
# HOST CONFIGURATION
# ===============================================
hostname: bingus
domain: local
fqdn: '{{ hostname }}.{{ domain }}'

# ===============================================
# PROXMOX API CONFIGURATION
# ===============================================
proxmox_api_url: https://{{ ansible_host }}:8006/api2/json
proxmox_api_insecure: true
proxmox_api_token_id: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          33363434343032323133356132363864366130376337373139626437336264616237323962323836
          6136363938633165393130363236323561376432323831310a613164303330336566616634333534
          35613135363038643864663534343331653033303539313566366636323538656665343836356438
          3031396539343862650a623063663835396462393363333863613266626432346133623666366430
          35363764303965623337353465336339356561663563636133323539323432383038
proxmox_api_token_secret: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          64643366646133653634636465616432353231376639353239393066653566656534383562653965
          6665653832623033303731303232353065653336623666350a353932366461613134633933356137
          66323131353931323532363135316632353036346534396161623339626237616239336661383661
          3235623633633362300a386633663633313936353766396266383334363631393938666532323561
          66653434636136623939333736653134653838613566313031373861336634666437363431366463
          3739613466303162353639333033343037316261346432343666

# ===============================================
# VM BACKUP CONFIGURATION
# ===============================================
backup_vms:
  - 100
