---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tailscale
spec:
  secretName: tailscale-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: ts.mirceanton.com
  dnsNames:
    - ts.mirceanton.com
    - "*.ts.mirceanton.com"
