---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: internal
spec:
  secretName: internal-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: home.mirceanton.com
  dnsNames:
    - home.mirceanton.com
    - "*.home.mirceanton.com"
