---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: services-pool
spec:
  autoAssign: false
  addresses:
    - 10.0.10.250/32 # envoy-services
    - 10.0.10.251/32 # davinci-postgres

---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: admin-pool
spec:
  autoAssign: false
  addresses:
    - "10.0.0.250/32" # envoy-admin
