---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./clustersecretstore.yaml
  - ./helmrelease.yaml
  - ./ocirepository.yaml
  - ./op-credentials.secret.sops.yaml
  - ./op-token.secret.sops.yaml
