---
- name: Configure Automaton
  hosts: automaton
  become: true

  pre_tasks:
    - name: Update and Upgrade System
      ansible.builtin.apt:
        upgrade: dist
        update_cache: true
        cache_valid_time: 3600

    - name: Install Utility Packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: "{{ apt_utility_state }}"
      loop: "{{ apt_utility_packages }}"

    - name: Set Hostname
      ansible.netcommon.net_system:
        hostname: "{{ hostname }}"
        domain_name: "{{ domain }}"
        name_servers: "{{ nameservers }}"

    - name: Set Timezone
      community.general.timezone:
        name: "{{ timezone }}"

    - name: Create required directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "u=rwx,g=rx,o=rx"
      loop:
        - "{{ docker_data_dir }}"
        - "{{ backup_dir_path }}"

  roles:
    # Installed required packages for local development
    - role: mirceanton.terraform
    - role: mirceanton.packer
    - role: mirceanton.ansible

    # Install docker to host services
    - role: mirceanton.docker

    - role: mirceanton.anacron
      vars:
        anacron_jobs:
          - "1  1  backup.daily  /bin/bash {{ backup_script_path }}"

  tasks:
    - name: Initialize The Docker Swarm
      community.docker.docker_swarm:
        state: "{{ docker_swarm_state }}"
        advertise_addr: "{{ docker_swarm_iface }}"

    - name: Create the Overlay Network
      community.docker.docker_network:
        name: "{{ docker_proxy_network }}"
        scope: swarm
        driver: overlay
