---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: envoy-gateway-config
spec:
  path: ./apps/network-system/envoy-gateway/config
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: network-system
  interval: 10m
  timeout: 5m
  prune: true
  wait: true
  dependsOn:
    - name: cert-manager-issuers
    - name: envoy-gateway
  decryption:
    provider: sops
