---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

resources:
  - ./namespace.yaml
  - ./cilium
  - ./descheduler
  - ./keda
  - ./metrics-server
  # - ./nvidia-device-plugin
  - ./reloader
