---

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

resources:
  - ./namespace.yaml
  - ./descheduler.ks.yaml
  - ./metrics-server.ks.yaml
  - ./reloader.ks.yaml
