---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: mktxp-config
    files:
      - files/_mktxp.conf
      - files/mktxp.conf

resources:
  - helm-release.yaml
  - oci-repository.yaml
  - credentials.secret.sops.yaml

  - grafana/folder.yaml
  - grafana/dashboard.yaml
