---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./firefly.ocirepository.yaml
  - ./firefly.helmrelease.yaml
  - ./firefly-settings.configmap.yaml
  - ./firefly-keys.secret.sops.yaml
  - ./firefly-data-importer-token.secret.sops.yaml

  - ./cnpg.yaml
  - ./postgres-backup.cronjob.yaml
  - ./postgres-restore.cronjob.yaml

  - ./dragonfly.yaml

configMapGenerator:
  - name: firefly-postgres-scripts
    files:
      - backup.sh=../../../../.scripts/postgres/backup.sh
      - restore.sh=../../../../.scripts/postgres/restore.sh

generatorOptions:
  disableNameSuffixHash: true
