---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./dragonfly.yaml
  - ./oci-repository.yaml
  - ./helm-release.yaml
  - ./penpot-secret.secret.sops.yaml
  - ./cnpg.yaml
  - ./postgres-backup.cronjob.yaml
  - ./postgres-restore.cronjob.yaml

configMapGenerator:
  - name: penpot-postgres-scripts
    files:
      - backup.sh=../../../../.scripts/postgres/backup.sh
      - restore.sh=../../../../.scripts/postgres/restore.sh

generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
