apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advertisement
spec:
  ipAddressPools: ["pool"]
  # Announce LoadBalancer IPs on the services VLAN interface only
  # This ensures ARP replies go out on the correct L2 network
  interfaces:
    - enp0s31f6.1010
