---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana-instance
spec:
  interval: 10m
  prune: true
  wait: true
  targetNamespace: monitoring-system

  path: ./apps/monitoring-system/grafana/instance
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system

  dependsOn:
    #? wait for the 1password-connect secret store to be ready
    - name: 1password-connect
      namespace: security-system
    - name: grafana-operator
    - name: openebs
      namespace: storage-system
