---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./postgres.cluster.yaml
  - ./postgres-backup.cronjob.yaml
  - ./postgres-restore.cronjob.yaml
  - ./davinci-postgres-password.secret.sops.yaml
  - ./davinci-postgres.pushsecret.yaml

configMapGenerator:
  - name: davinci-postgres-scripts
    files:
      - backup.sh=../../../../.scripts/postgres/backup.sh
      - restore.sh=../../../../.scripts/postgres/restore.sh

generatorOptions:
  disableNameSuffixHash: true
