---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./postgres.cluster.yaml
  - ./postgres-backup.cronjob.yaml
  - ./postgres-restore.cronjob.yaml

configMapGenerator:
  - name: davinci-postgres-scripts
    files:
      - scripts/backup.sh
      - scripts/restore.sh

generatorOptions:
  disableNameSuffixHash: true
