---
apiVersion: v1
kind: ConfigMap
metadata:
  name: z2m-config
data:
  TZ: Europe/Bucharest
  ZIGBEE2MQTT_DATA: /config

  # Logging Configuration
  ZIGBEE2MQTT_CONFIG_ADVANCED_LAST_SEEN: "ISO_8601"
  ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_LEVEL: "info" # debug
  ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_OUTPUT: '["console"]'

  ZIGBEE2MQTT_CONFIG_AVAILABILITY_ACTIVE_TIMEOUT: "60"
  ZIGBEE2MQTT_CONFIG_AVAILABILITY_PASSIVE_TIMEOUT: "2000"
  ZIGBEE2MQTT_CONFIG_DEVICE_OPTIONS_RETAIN: "true"
  ZIGBEE2MQTT_CONFIG_PERMIT_JOIN: "false"

  # Frontend Configuration
  ZIGBEE2MQTT_CONFIG_FRONTEND_ENABLED: "true"
  ZIGBEE2MQTT_CONFIG_FRONTEND_URL: "https://z2m.home.mirceanton.com"
  ZIGBEE2MQTT_CONFIG_FRONTEND_PACKAGE: "zigbee2mqtt-windfront" # or zigbee2mqtt-frontend (old)
  ZIGBEE2MQTT_CONFIG_FRONTEND_PORT: "80"

  # Home Assistant Configuration
  ZIGBEE2MQTT_CONFIG_HOMEASSISTANT_ENABLED: "true"
  ZIGBEE2MQTT_CONFIG_HOMEASSISTANT_DISCOVERY_TOPIC: "homeassistant"
  ZIGBEE2MQTT_CONFIG_HOMEASSISTANT_STATUS_TOPIC: "homeassistant/status"

  # MQTT Configuration
  ZIGBEE2MQTT_CONFIG_MQTT_BASE_TOPIC: "zigbee2mqtt"
  ZIGBEE2MQTT_CONFIG_MQTT_INCLUDE_DEVICE_INFORMATION: "true"
  ZIGBEE2MQTT_CONFIG_MQTT_KEEPALIVE: "60"
  ZIGBEE2MQTT_CONFIG_MQTT_REJECT_UNAUTHORIZED: "true"
  ZIGBEE2MQTT_CONFIG_MQTT_SERVER: "mqtt://mosquitto.home-automation.svc.cluster.local:1883"
  ZIGBEE2MQTT_CONFIG_MQTT_VERSION: "5"

  # Serial Device Configuration
  ZIGBEE2MQTT_CONFIG_SERIAL_PORT: "tcp://10.0.0.99:6638"
  ZIGBEE2MQTT_CONFIG_SERIAL_BAUDRATE: "115200"
  ZIGBEE2MQTT_CONFIG_SERIAL_ADAPTER: "ember"
  ZIGBEE2MQTT_CONFIG_SERIAL_RTSCTS: "false"
  ZIGBEE2MQTT_CONFIG_SERIAL_DISABLE_LED: "false"
