title: "Home Dashboard"
subtitle: "mirceanton.com"
header: true
footer: false
columns: 3
connectivityCheck: true

links: []

services:
  - name: "Media"
    icon: "fas fa-photo-video"
    items:
      - name: "Jellyfin"
        subtitle: "Media Server"
        url: "https://jellyfin.home.mirceanton.com"
        target: "_blank"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/jellyfin.png"
      - name: "Navidrome"
        subtitle: "Music Server"
        url: "https://navidrome.home.mirceanton.com"
        target: "_blank"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/navidrome.png"
      - name: "Booklore"
        subtitle: "Book Library"
        url: "https://booklore.home.mirceanton.com"
        target: "_blank"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/calibre-web.png"
      - name: "Karakeep"
        subtitle: "Bookmark Manager"
        url: "https://karakeep.home.mirceanton.com"
        target: "_blank"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/karakeep.png"

  - name: "Home Automation"
    icon: "fas fa-home"
    items:
      - name: "Home Assistant"
        subtitle: "Home Automation"
        url: "https://homeassistant.home.mirceanton.com"
        target: "_blank"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/home-assistant.png"
      - name: "Zigbee2MQTT"
        subtitle: "Zigbee Bridge"
        url: "https://z2m.home.mirceanton.com"
        target: "_blank"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/zigbee2mqtt.png"

  - name: "Finances"
    icon: "fas fa-wallet"
    items:
      - name: "Firefly III"
        subtitle: "Financial Manager"
        url: "https://firefly.home.mirceanton.com"
        target: "_blank"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/firefly-iii.png"

  - name: "Downloads"
    icon: "fa-solid fa-skull-crossbones"
    items:
      - name: "Sonarr"
        subtitle: "TV Shows Management"
        url: "https://sonarr.home.mirceanton.com"
        target: "_blank"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/sonarr.png"
      - name: "Radarr"
        subtitle: "Movie Management"
        url: "https://radarr.home.mirceanton.com"
        target: "_blank"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/radarr.png"
      - name: "Lidarr"
        subtitle: "Music Management"
        url: "https://lidarr.home.mirceanton.com"
        target: "_blank"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/lidarr.png"
      - name: "Shelfmark"
        subtitle: "Bookmarks Manager"
        url: "https://shelfmark.home.mirceanton.com"
        target: "_blank"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/linkding.png"
      - name: "Prowlarr"
        subtitle: "Indexer Manager"
        url: "https://prowlarr.home.mirceanton.com"
        target: "_blank"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/prowlarr.png"
      - name: "qBittorrent"
        subtitle: "Torrent Client"
        url: "https://torrent.home.mirceanton.com"
        target: "_blank"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/qbittorrent.png"

  - name: "Miscellaneous"
    icon: "fas fa-code"
    items:
      - name: "IT-Tools"
        subtitle: "Various Utilities"
        url: "https://tools.home.mirceanton.com"
        target: "_blank"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/it-tools.png"
