title: "Home Dashboard"
subtitle: ""
header: true
footer: false
columns: 5
connectivityCheck: true

links: []

services:
  - name: "Media"
    icon: "fas fa-photo-video"
    items:
      - name: "Jellyfin"
        subtitle: "Media Server"
        url: "https://jellyfin.home.mirceanton.com"
        target: "_blank"
        logo: "assets/icons/jellyfin.svg"
      - name: "Navidrome"
        subtitle: "Music Server"
        url: "https://navidrome.home.mirceanton.com"
        target: "_blank"
        logo: "assets/icons/navidrome.svg"
      - name: "Booklore"
        subtitle: "Book Library"
        url: "https://booklore.home.mirceanton.com"
        target: "_blank"
        logo: "assets/icons/booklore.svg"
      - name: "Karakeep"
        subtitle: "Bookmark Manager"
        url: "https://karakeep.home.mirceanton.com"
        target: "_blank"
        logo: "assets/icons/karakeep.svg"

  - name: "Home Automation"
    icon: "fas fa-home"
    items:
      - name: "Home Assistant"
        subtitle: "Home Automation"
        url: "https://homeassistant.home.mirceanton.com"
        target: "_blank"
        logo: "assets/icons/home-assistant.svg"
      - name: "Zigbee2MQTT"
        subtitle: "Zigbee Bridge"
        url: "https://z2m.home.mirceanton.com"
        target: "_blank"
        logo: "assets/icons/zigbee2mqtt.svg"

  - name: "Finances"
    icon: "fas fa-wallet"
    items:
      - name: "Firefly III"
        subtitle: "Financial Manager"
        url: "https://firefly.home.mirceanton.com"
        target: "_blank"
        logo: "assets/icons/firefly-iii.svg"

  - name: "Downloads"
    icon: "fa-solid fa-skull-crossbones"
    items:
      - name: "Sonarr"
        subtitle: "TV Shows Management"
        url: "https://sonarr.home.mirceanton.com"
        target: "_blank"
        logo: "assets/icons/sonarr.svg"
      - name: "Radarr"
        subtitle: "Movie Management"
        url: "https://radarr.home.mirceanton.com"
        target: "_blank"
        logo: "assets/icons/radarr.svg"
      - name: "Lidarr"
        subtitle: "Music Management"
        url: "https://lidarr.home.mirceanton.com"
        target: "_blank"
        logo: "assets/icons/lidarr.svg"
      - name: "Shelfmark"
        subtitle: "Bookmarks Manager"
        url: "https://shelfmark.home.mirceanton.com"
        target: "_blank"
        logo: https://raw.githubusercontent.com/calibrain/shelfmark/refs/heads/main/src/frontend/public/logo.png #!FIXME Use local asset
      - name: "Prowlarr"
        subtitle: "Indexer Manager"
        url: "https://prowlarr.home.mirceanton.com"
        target: "_blank"
        logo: "assets/icons/prowlarr.svg"
      - name: "qBittorrent"
        subtitle: "Torrent Client"
        url: "https://torrent.home.mirceanton.com"
        target: "_blank"
        logo: "assets/icons/qbittorrent.svg"

  - name: "Miscellaneous"
    icon: "fas fa-code"
    items:
      - name: "IT-Tools"
        subtitle: "Various Utilities"
        url: "https://tools.home.mirceanton.com"
        target: "_blank"
        logo: "assets/icons/it-tools.svg"
