---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: downloads

resources:
  - ./namespace.yaml
  - ./autobrr
  - ./bazarr
  - ./flaresolverr
  - ./lidarr
  - ./prowlarr
  - ./qbittorrent
  - ./radarr
  - ./sabnzbd
  - ./sonarr
