---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: downloads

resources:
  - ./namespace.yaml
  - ./flaresolverr
  - ./lidarr
  - ./prowlarr
  - ./qbittorrent
  - ./qui
  - ./radarr
  - ./shelfmark
  - ./sonarr
  - ./tdarr
