---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./cnpg.yaml
  - ./dragonfly.yaml

  - ./oci-repository.yaml
  - ./immich-server.helm-release.yaml
  - ./immich-ml.helm-release.yaml
  - ./pvc.yaml

  - ./postgres-backup.cronjob.yaml
  - ./postgres-restore.cronjob.yaml

configMapGenerator:
  - name: immich-postgres-scripts
    files:
      - backup.sh=../../../../.scripts/postgres/backup.sh
      - restore.sh=../../../../.scripts/postgres/restore.sh

generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
