---
- name: Deploy Traefik
  ansible.builtin.include_role:
    name: mirceanton.docker_stack_deploy
  vars:
    docker_stack_deploy_name: "{{ traefik_stack_name }}"
    docker_stack_deploy_root_dir_path: "{{ traefik_stack_data_dir_path }}"
    docker_stack_deploy_root_dir_mode: "{{ traefik_stack_data_dir_mode }}"
    docker_stack_deploy_additional_dirs: "{{ traefik_stack_additional_dirs }}"
    docker_stack_deploy_template_files: "{{ traefik_stack_template_files }}"

- name: "[traefik] Add local DNS entry"
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "127.0.0.1 {{ traefik_stack_name }}.{{ fqdn }}"
