---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./booklore.ocirepository.yaml
  - ./booklore.helmrelease.yaml
  - ./booklore.secret.sops.yaml

  - ./mariadb.ocirepository.yaml
  - ./mariadb.helmrelease.yaml
  - ./mariadb-backup.cronjob.yaml
  - ./mariadb-restore.cronjob.yaml

configMapGenerator:
  - name: booklore-mariadb-scripts
    files:
      - scripts/backup.sh
      - scripts/restore.sh

generatorOptions:
  disableNameSuffixHash: true
